#!/bin/bash

if command -v apt-get &> /dev/null
then
    sudo apt-get update
    sudo apt-get install -y neovim git
fi

## Swap caps and escape for good :)
if command -v dconf &> /dev/null
then
    dconf write /org/gnome/desktop/input-sources/xkb-options "['caps:swapescape']"
fi
