#!/bin/bash


if command -v apt-get &> /dev/null
then
    sudo apt-get update
    sudo apt-get install -y \
	    neovim \
	    git \
	    python3-pip \
	    python3-venv \
	    zsh \
	    htop \
	    trash-cli \
	    ffmpeg \
	    python3-tk

fi

chsh -s /bin/zsh


python3 -m pip install pipx
pipx install csvkit
pipx install qtconsole
pipx runpip qtconsole install pyqt5
pipx install youtube-dl


## Swap caps and escape for good :)
if command -v dconf &> /dev/null
then
    dconf write /org/gnome/desktop/input-sources/xkb-options "['caps:swapescape']"
fi
