#!/bin/bash


if command -v apt-get &> /dev/null
then
    sudo apt-get update
    sudo apt-get install -y \
	    neovim \
	    git \
	    python3-pip \
	    python3-venv \
	    zsh \
	    htop \
	    trash-cli \
	    ffmpeg \
	    python3-tk
    	    snap \
	    fzf \

fi

chsh -s /bin/zsh

snap install universal-ctags

curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
sudo apt-get install -y nodejs npm

python3 -m pip install pipx
pipx install csvkit
pipx install qtconsole
pipx runpip qtconsole install pyqt5
pipx install youtube-dl


## Swap caps and escape for good :)
if command -v dconf &> /dev/null
then
    dconf write /org/gnome/desktop/input-sources/xkb-options "['caps:swapescape']"
fi

## Docker

sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88

sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io


sudo groupadd docker
sudo usermod -aG docker $USER

sudo add-apt-repository ppa:nextcloud-devs/client
sudo apt-get update
sudo apt-get install -y nextcloud-desktop
